// This file is auto-generated by Payload during build.
// During development, it will be regenerated automatically.
// Placeholder for the import map that Payload CMS generates.
export const importMap = {}
