/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    services: Service;
    locations: Location;
    leads: Lead;
    blogs: Blog;
    news: News;
    faqs: Faq;
    testimonials: Testimonial;
    gallery: Gallery;
    lawyers: Lawyer;
    'lawyer-media': LawyerMedia;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    lawyers: LawyersSelect<false> | LawyersSelect<true>;
    'lawyer-media': LawyerMediaSelect<false> | LawyerMediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Only developers can change user roles.
   */
  role: 'developer' | 'admin' | 'blogManager';
  /**
   * Auto-synced Supabase Auth user ID
   */
  supabaseId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for SEO and accessibility. Describe what the image shows.
   */
  alt: string;
  caption?: string | null;
  /**
   * Optional SEO-optimized title for the media asset.
   */
  seoTitle?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path for this page. For dynamic pages, this is auto-generated.
   */
  slug: string;
  /**
   * 🎨 Build your webpage here! Click "Add Block" below to stack sections. ⚠️ CRITICAL WARNING: If you forget a required field, hit Save, and get an error, DO NOT hit save again. Delete the blocks and re-add them, or start a new page, otherwise it will crash the save pipeline!
   */
  layout: (
    | {
        layoutStyle: 'standard' | 'withLeadForm';
        /**
         * Main headline
         */
        heading: string;
        /**
         * Supporting text below the headline
         */
        subheading?: string | null;
        backgroundType?: ('image' | 'color') | null;
        /**
         * Upload a background image for the hero section.
         */
        backgroundImage?: (number | null) | Media;
        backgroundColor?: ('white' | 'black' | 'gold') | null;
        textColorTheme?: ('auto' | 'light' | 'dark') | null;
        /**
         * Display the City + Legal Matter search bar below the hero text.
         */
        showSearchBar?: boolean | null;
        /**
         * e.g., "Book a Consultation"
         */
        ctaText?: string | null;
        ctaLink?: string | null;
        secondaryCta?: {
          text?: string | null;
          link?: string | null;
        };
        /**
         * Choose the layout style for the standard hero section.
         */
        style?: ('fullWidth' | 'split' | 'centered') | null;
        /**
         * Display the statistics bar below the hero (e.g. 25k+ Consultations).
         */
        showStatsBar?: boolean | null;
        /**
         * Statistics shown in the bar below the hero section.
         */
        stats?:
          | {
              /**
               * Select an icon to display
               */
              icon: 'scale' | 'check' | 'users' | 'clock' | 'shield' | 'star' | 'file' | 'trophy';
              /**
               * The stat value (e.g. "25k+", "98%", "1.2k+")
               */
              value: string;
              /**
               * Label below the value (e.g. "Consultations", "Success Rate")
               */
              label: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        /**
         * Full-featured editor supporting headings, lists, formatting, links, and inline images.
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        maxWidth?: ('narrow' | 'default' | 'wide' | 'full') | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richContent';
      }
    | {
        heading?: string | null;
        description?: string | null;
        source?: ('manual' | 'auto') | null;
        /**
         * Manually select which FAQs to display
         */
        faqs?: (number | Faq)[] | null;
        /**
         * Auto-fetch FAQs matching this scope
         */
        autoScope?: ('global' | 'service' | 'location' | 'page') | null;
        style?: ('accordion' | 'list') | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | {
        /**
         * Choose if this section looks like feature cards or a trust/stats bar.
         */
        sectionStyle?: ('cards' | 'statsBar') | null;
        heading?: string | null;
        description?: string | null;
        items: {
          title: string;
          description?: string | null;
          icon?: (number | null) | Media;
          id?: string | null;
        }[];
        columns?: ('2' | '3' | '4') | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'highlights';
      }
    | {
        heading: string;
        subheading?: string | null;
        /**
         * Add or manage the benefit cards in this section.
         */
        benefits?:
          | {
              title: string;
              description: string;
              icon?: ('phone' | 'strategy' | 'gavel' | 'trending' | 'laptop' | 'payments' | 'shield' | 'users') | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Subtle trust indicators shown at the bottom of the section.
         */
        trustBadges?:
          | {
              badgeText: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'whyChooseUs';
      }
    | {
        badge?: string | null;
        heading: string;
        subheading?: string | null;
        /**
         * Dynamic grid of registration service cards.
         */
        cards?:
          | {
              title: string;
              description: string;
              icon?:
                | (
                    | 'wallet'
                    | 'corporate'
                    | 'restaurant'
                    | 'business'
                    | 'public'
                    | 'verified'
                    | 'premium'
                    | 'policy'
                    | 'shield'
                    | 'gavel'
                    | 'speed'
                  )
                | null;
              /**
               * URL or path to redirect when clicked (e.g., /services/gst-registration)
               */
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        ctaSection?: {
          ctaHeading?: string | null;
          ctaSubheading?: string | null;
          ctaButtonText?: string | null;
          ctaLink?: string | null;
        };
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'registrationLicenses';
      }
    | {
        processLabel?: string | null;
        heading: string;
        backgroundImage: number | Media;
        quoteText?: string | null;
        /**
         * Manage exactly 3 steps to guide the user through the process.
         */
        steps?:
          | {
              title: string;
              description: string;
              icon?: ('document' | 'handshake' | 'gavel' | 'scale' | 'shield') | null;
              id?: string | null;
            }[]
          | null;
        ctaText?: string | null;
        ctaLink?: string | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'howItWorks';
      }
    | {
        formHeading?: string | null;
        formSubheading?: string | null;
        image: number | Media;
        imageHeading?: string | null;
        imageSubheading?: string | null;
        trustText?: string | null;
        ctaButtonText?: string | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'consultation';
      }
    | {
        heading: string;
        description?: string | null;
        primaryButton: {
          text: string;
          link: string;
        };
        secondaryButton?: {
          text?: string | null;
          link?: string | null;
        };
        backgroundImage?: (number | null) | Media;
        style?: ('default' | 'banner' | 'card') | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        heading?: string | null;
        source?: ('latest' | 'byService' | 'byLocation' | 'byCategory' | 'manual') | null;
        service?: (number | null) | Service;
        location?: (number | null) | Location;
        category?: string | null;
        selectedBlogs?: (number | Blog)[] | null;
        limit?: number | null;
        layout?: ('grid' | 'list' | 'carousel') | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'blogFeed';
      }
    | {
        heading?: string | null;
        source?: ('latest' | 'byService' | 'byLocation' | 'byCategory' | 'manual') | null;
        service?: (number | null) | Service;
        location?: (number | null) | Location;
        category?: string | null;
        selectedNews?: (number | News)[] | null;
        limit?: number | null;
        layout?: ('grid' | 'list' | 'carousel') | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'newsFeed';
      }
    | {
        heading?: string | null;
        source?: ('manual' | 'collection') | null;
        images?:
          | {
              image: number | Media;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Select a gallery from the Gallery collection
         */
        gallery?: (number | null) | Gallery;
        layout?: ('grid' | 'masonry' | 'carousel') | null;
        columns?: ('2' | '3' | '4') | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'galleryBlock';
      }
    | {
        heading?: string | null;
        description?: string | null;
        /**
         * Select testimonials to display
         */
        testimonials?: (number | Testimonial)[] | null;
        /**
         * Max testimonials to show (if none selected manually, fetches latest)
         */
        limit?: number | null;
        layout?: ('grid' | 'carousel') | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonialsBlock';
      }
    | ServicesCarouselBlockType
    | {
        heading: string;
        /**
         * Select and reorder the lawyers you want to feature in this carousel. Only approved lawyers are shown.
         */
        lawyers: (number | Lawyer)[];
        autoplay?: boolean | null;
        /**
         * Transition interval in milliseconds (e.g., 5000 for 5 seconds)
         */
        interval?: number | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'lawyersCarousel';
      }
    | CodeSnippetBlockType
    | LogosBlockType
    | {
        heading?: string | null;
        description?: string | null;
        items?:
          | {
              title: string;
              icon?: ('document' | 'location' | 'calendar' | 'camera' | 'users' | 'shield') | null;
              content: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              /**
               * Optional small note at the bottom (e.g., "Important: ...")
               */
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Control where and on which devices this block appears.
         */
        visibility?: {
          showOnDesktop?: boolean | null;
          showOnMobile?: boolean | null;
          targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
          targetPages?: (number | Page)[] | null;
          targetServices?: (number | Service)[] | null;
          targetLocations?: (number | Location)[] | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'documents';
      }
  )[];
  /**
   * 🔗 Only fill this out if this is a dedicated Service Page (e.g., "Court Marriage Services"). Links this page to that parent service.
   */
  service?: (number | null) | Service;
  /**
   * 📍 Only fill this out if this is a dedicated Location Page (e.g., "Lawyers in Delhi").
   */
  location?: (number | null) | Location;
  /**
   * Manually assign blogs to show on this page
   */
  assignedBlogs?: (number | Blog)[] | null;
  /**
   * Manually assign news to show on this page
   */
  assignedNews?: (number | News)[] | null;
  /**
   * Manually assign FAQs to show on this page
   */
  assignedFAQs?: (number | Faq)[] | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsMeta?: ('index,follow' | 'noindex,follow' | 'index,nofollow' | 'noindex,nofollow') | null;
    schemaMarkup?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  status?: ('draft' | 'published') | null;
  /**
   * Use Custom Page for Homepage, About, Contact, etc.
   */
  pageType?: ('custom' | 'service' | 'location' | 'serviceLocation') | null;
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL-friendly identifier (e.g., "court-marriage-lawyer")
   */
  slug: string;
  /**
   * 🎨 Using Blocks will OVERRIDE the legacy fixed fields below (banner, content, highlights) on the frontend. Use this to design flexible service pages!
   */
  layout?:
    | (
        | {
            layoutStyle: 'standard' | 'withLeadForm';
            /**
             * Main headline
             */
            heading: string;
            /**
             * Supporting text below the headline
             */
            subheading?: string | null;
            backgroundType?: ('image' | 'color') | null;
            /**
             * Upload a background image for the hero section.
             */
            backgroundImage?: (number | null) | Media;
            backgroundColor?: ('white' | 'black' | 'gold') | null;
            textColorTheme?: ('auto' | 'light' | 'dark') | null;
            /**
             * Display the City + Legal Matter search bar below the hero text.
             */
            showSearchBar?: boolean | null;
            /**
             * e.g., "Book a Consultation"
             */
            ctaText?: string | null;
            ctaLink?: string | null;
            secondaryCta?: {
              text?: string | null;
              link?: string | null;
            };
            /**
             * Choose the layout style for the standard hero section.
             */
            style?: ('fullWidth' | 'split' | 'centered') | null;
            /**
             * Display the statistics bar below the hero (e.g. 25k+ Consultations).
             */
            showStatsBar?: boolean | null;
            /**
             * Statistics shown in the bar below the hero section.
             */
            stats?:
              | {
                  /**
                   * Select an icon to display
                   */
                  icon: 'scale' | 'check' | 'users' | 'clock' | 'shield' | 'star' | 'file' | 'trophy';
                  /**
                   * The stat value (e.g. "25k+", "98%", "1.2k+")
                   */
                  value: string;
                  /**
                   * Label below the value (e.g. "Consultations", "Success Rate")
                   */
                  label: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            /**
             * Full-featured editor supporting headings, lists, formatting, links, and inline images.
             */
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            maxWidth?: ('narrow' | 'default' | 'wide' | 'full') | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richContent';
          }
        | {
            heading?: string | null;
            description?: string | null;
            source?: ('manual' | 'auto') | null;
            /**
             * Manually select which FAQs to display
             */
            faqs?: (number | Faq)[] | null;
            /**
             * Auto-fetch FAQs matching this scope
             */
            autoScope?: ('global' | 'service' | 'location' | 'page') | null;
            style?: ('accordion' | 'list') | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            /**
             * Choose if this section looks like feature cards or a trust/stats bar.
             */
            sectionStyle?: ('cards' | 'statsBar') | null;
            heading?: string | null;
            description?: string | null;
            items: {
              title: string;
              description?: string | null;
              icon?: (number | null) | Media;
              id?: string | null;
            }[];
            columns?: ('2' | '3' | '4') | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'highlights';
          }
        | {
            heading: string;
            subheading?: string | null;
            /**
             * Add or manage the benefit cards in this section.
             */
            benefits?:
              | {
                  title: string;
                  description: string;
                  icon?:
                    | ('phone' | 'strategy' | 'gavel' | 'trending' | 'laptop' | 'payments' | 'shield' | 'users')
                    | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Subtle trust indicators shown at the bottom of the section.
             */
            trustBadges?:
              | {
                  badgeText: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'whyChooseUs';
          }
        | {
            badge?: string | null;
            heading: string;
            subheading?: string | null;
            /**
             * Dynamic grid of registration service cards.
             */
            cards?:
              | {
                  title: string;
                  description: string;
                  icon?:
                    | (
                        | 'wallet'
                        | 'corporate'
                        | 'restaurant'
                        | 'business'
                        | 'public'
                        | 'verified'
                        | 'premium'
                        | 'policy'
                        | 'shield'
                        | 'gavel'
                        | 'speed'
                      )
                    | null;
                  /**
                   * URL or path to redirect when clicked (e.g., /services/gst-registration)
                   */
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            ctaSection?: {
              ctaHeading?: string | null;
              ctaSubheading?: string | null;
              ctaButtonText?: string | null;
              ctaLink?: string | null;
            };
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'registrationLicenses';
          }
        | {
            processLabel?: string | null;
            heading: string;
            backgroundImage: number | Media;
            quoteText?: string | null;
            /**
             * Manage exactly 3 steps to guide the user through the process.
             */
            steps?:
              | {
                  title: string;
                  description: string;
                  icon?: ('document' | 'handshake' | 'gavel' | 'scale' | 'shield') | null;
                  id?: string | null;
                }[]
              | null;
            ctaText?: string | null;
            ctaLink?: string | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'howItWorks';
          }
        | {
            formHeading?: string | null;
            formSubheading?: string | null;
            image: number | Media;
            imageHeading?: string | null;
            imageSubheading?: string | null;
            trustText?: string | null;
            ctaButtonText?: string | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'consultation';
          }
        | {
            heading: string;
            description?: string | null;
            primaryButton: {
              text: string;
              link: string;
            };
            secondaryButton?: {
              text?: string | null;
              link?: string | null;
            };
            backgroundImage?: (number | null) | Media;
            style?: ('default' | 'banner' | 'card') | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            source?: ('latest' | 'byService' | 'byLocation' | 'byCategory' | 'manual') | null;
            service?: (number | null) | Service;
            location?: (number | null) | Location;
            category?: string | null;
            selectedBlogs?: (number | Blog)[] | null;
            limit?: number | null;
            layout?: ('grid' | 'list' | 'carousel') | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogFeed';
          }
        | {
            heading?: string | null;
            source?: ('latest' | 'byService' | 'byLocation' | 'byCategory' | 'manual') | null;
            service?: (number | null) | Service;
            location?: (number | null) | Location;
            category?: string | null;
            selectedNews?: (number | News)[] | null;
            limit?: number | null;
            layout?: ('grid' | 'list' | 'carousel') | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsFeed';
          }
        | {
            heading?: string | null;
            source?: ('manual' | 'collection') | null;
            images?:
              | {
                  image: number | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Select a gallery from the Gallery collection
             */
            gallery?: (number | null) | Gallery;
            layout?: ('grid' | 'masonry' | 'carousel') | null;
            columns?: ('2' | '3' | '4') | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'galleryBlock';
          }
        | {
            heading?: string | null;
            description?: string | null;
            /**
             * Select testimonials to display
             */
            testimonials?: (number | Testimonial)[] | null;
            /**
             * Max testimonials to show (if none selected manually, fetches latest)
             */
            limit?: number | null;
            layout?: ('grid' | 'carousel') | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonialsBlock';
          }
        | ServicesCarouselBlockType
        | {
            heading: string;
            /**
             * Select and reorder the lawyers you want to feature in this carousel. Only approved lawyers are shown.
             */
            lawyers: (number | Lawyer)[];
            autoplay?: boolean | null;
            /**
             * Transition interval in milliseconds (e.g., 5000 for 5 seconds)
             */
            interval?: number | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'lawyersCarousel';
          }
        | CodeSnippetBlockType
        | LogosBlockType
        | {
            heading?: string | null;
            description?: string | null;
            items?:
              | {
                  title: string;
                  icon?: ('document' | 'location' | 'calendar' | 'camera' | 'users' | 'shield') | null;
                  content: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  /**
                   * Optional small note at the bottom (e.g., "Important: ...")
                   */
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Control where and on which devices this block appears.
             */
            visibility?: {
              showOnDesktop?: boolean | null;
              showOnMobile?: boolean | null;
              targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
              targetPages?: (number | Page)[] | null;
              targetServices?: (number | Service)[] | null;
              targetLocations?: (number | Location)[] | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'documents';
          }
      )[]
    | null;
  banner?: (number | null) | Media;
  /**
   * Select the cities where this service is actively offered. Only selected cities will generate live landing pages.
   */
  activeLocations?: (number | Location)[] | null;
  /**
   * If enabled, this service will appear in the "Services" menu in the header.
   */
  showInHeader?: boolean | null;
  /**
   * Lower numbers appear first in the dropdown.
   */
  menuOrder?: number | null;
  /**
   * Which mega-dropdown should this appear in?
   */
  navDropdown?: ('find-a-lawyer' | 'legal-matter' | 'none') | null;
  /**
   * Group heading inside the dropdown (e.g. "Family / Personal", "Criminal / Writ"). Items with the same heading are grouped together.
   */
  navCategory?: string | null;
  /**
   * Controls the order of categories in the dropdown. Lower = first.
   */
  navCategoryOrder?: number | null;
  /**
   * Custom label shown in the dropdown (leave blank to use the service title).
   */
  navLabel?: string | null;
  /**
   * Legacy icon upload (optional). Prefer using the Native Legal Icon below.
   */
  icon?: (number | null) | Media;
  /**
   * Select a highly optimized SVG icon to use for standard layout cards.
   */
  uiIcon?:
    | (
        | 'gavel'
        | 'handshake'
        | 'scale'
        | 'building'
        | 'file-contract'
        | 'shield'
        | 'user-tie'
        | 'users'
        | 'calculator'
        | 'home'
        | 'briefcase'
        | 'landmark'
        | 'money-bill'
        | 'book'
        | 'stamp'
      )
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Key highlights / features of this service
   */
  highlights?:
    | {
        title: string;
        description?: string | null;
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Assign existing FAQs to this service
   */
  faqs?: (number | Faq)[] | null;
  /**
   * Search engine optimization fields
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsMeta?: ('index,follow' | 'noindex,follow' | 'index,nofollow' | 'noindex,nofollow') | null;
    schemaMarkup?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  /**
   * URL-friendly name (e.g., "delhi", "saket")
   */
  slug: string;
  type: 'country' | 'state' | 'city' | 'area';
  /**
   * Parent location (e.g., City → State, Area → City)
   */
  parent?: (number | null) | Location;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Where this FAQ applies. Global FAQs can be reused everywhere.
   */
  scope: 'global' | 'service' | 'location' | 'page';
  /**
   * Assign to a specific service
   */
  service?: (number | null) | Service;
  /**
   * Assign to a specific location
   */
  location?: (number | null) | Location;
  /**
   * Assign to a specific page
   */
  page?: (number | null) | Page;
  /**
   * Lower numbers appear first
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  /**
   * URL-friendly blog identifier
   */
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short summary for listing pages and SEO
   */
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  author?: (number | null) | User;
  categories?:
    | {
        category: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Assign blog to specific services for smart targeting
   */
  services?: (number | Service)[] | null;
  /**
   * Assign blog to specific locations for smart targeting
   */
  locations?: (number | Location)[] | null;
  status?: ('draft' | 'published') | null;
  publishedDate?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsMeta?: ('index,follow' | 'noindex,follow' | 'index,nofollow' | 'noindex,nofollow') | null;
    schemaMarkup?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  author?: (number | null) | User;
  categories?:
    | {
        category: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  services?: (number | Service)[] | null;
  locations?: (number | Location)[] | null;
  status?: ('draft' | 'published') | null;
  publishedDate?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    keywords?: string | null;
    ogImage?: (number | null) | Media;
    canonicalUrl?: string | null;
    robotsMeta?: ('index,follow' | 'noindex,follow' | 'index,nofollow' | 'noindex,nofollow') | null;
    schemaMarkup?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  /**
   * e.g., "Office", "Events", "Court Proceedings"
   */
  category?: string | null;
  images: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  /**
   * e.g., "Business Owner" or "Client"
   */
  designation?: string | null;
  content: string;
  rating?: number | null;
  photo?: (number | null) | Media;
  /**
   * Optionally link to a service this testimonial is about
   */
  service?: (number | null) | Service;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesCarouselBlockType".
 */
export interface ServicesCarouselBlockType {
  heading: string;
  /**
   * Add and reorder services for the carousel. You can also override the default service icon here.
   */
  items: {
    service: number | Service;
    /**
     * Pick a React icon for this card. Leave empty to use the service's default icon.
     */
    overrideIcon?:
      | (
          | ''
          | 'gavel'
          | 'handshake'
          | 'scale'
          | 'building'
          | 'file-contract'
          | 'shield'
          | 'user-tie'
          | 'users'
          | 'calculator'
          | 'home'
          | 'briefcase'
          | 'landmark'
          | 'money-bill'
          | 'book'
          | 'stamp'
        )
      | null;
    /**
     * Optional: Override the default service banner for this card.
     */
    backgroundImage?: (number | null) | Media;
    /**
     * Optional: Override the default highlights. If left empty, highlights from the service will be used.
     */
    highlights?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * Control where and on which devices this block appears.
   */
  visibility?: {
    showOnDesktop?: boolean | null;
    showOnMobile?: boolean | null;
    targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
    targetPages?: (number | Page)[] | null;
    targetServices?: (number | Service)[] | null;
    targetLocations?: (number | Location)[] | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'servicesCarousel';
}
/**
 * Manage lawyer profiles, approvals, and sponsored status.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lawyers".
 */
export interface Lawyer {
  id: number;
  name: string;
  /**
   * URL-friendly name (auto-generated from name)
   */
  slug: string;
  /**
   * Email address (must be unique)
   */
  email: string;
  phone?: string | null;
  /**
   * Supabase Auth user ID (auto-linked)
   */
  supabaseId?: string | null;
  /**
   * Only approved lawyers appear on the public site.
   */
  status: 'pending_review' | 'approved' | 'rejected' | 'suspended';
  /**
   * Internal note (e.g., rejection reason). Not shown to public.
   */
  statusNote?: string | null;
  /**
   * Sponsored lawyers get premium placement and a gold badge.
   */
  isSponsored?: boolean | null;
  /**
   * Premium partners get additional visibility & branding.
   */
  isPremiumPartner?: boolean | null;
  photo?: (number | null) | LawyerMedia;
  /**
   * e.g., "Senior Advocate", "Family Law Expert"
   */
  designation?: string | null;
  /**
   * Tell clients about your expertise, background, and approach.
   */
  bio?: string | null;
  /**
   * Bar Council registration/enrollment number for verification.
   */
  barCouncilId?: string | null;
  /**
   * Years of experience
   */
  experience?: number | null;
  /**
   * e.g., "₹500 - ₹2000"
   */
  consultationFee?: string | null;
  /**
   * e.g., "Mon-Fri, 9AM-6PM"
   */
  availableHours?: string | null;
  /**
   * Display location (e.g., "Connaught Place, New Delhi")
   */
  locationText?: string | null;
  /**
   * Courts where the lawyer practices (e.g., "District Civil Court-1, Jamshedpur")
   */
  courts?: string | null;
  /**
   * Link to a city/location for filtering.
   */
  location?: (number | null) | Location;
  /**
   * Languages this lawyer can communicate in.
   */
  languages?:
    | {
        language: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Law degrees and qualifications.
   */
  education?:
    | {
        /**
         * e.g., "LLB", "LLM", "BA LLB"
         */
        degree: string;
        college: string;
        /**
         * Year of graduation
         */
        year?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Each specialization links to a service. This determines which service pages show this lawyer.
   */
  specializations?:
    | {
        /**
         * Link to a service (e.g., Divorce, Property, Criminal Law)
         */
        service: number | Service;
        /**
         * Custom title (e.g., "Divorce Lawyer", "Property Dispute Expert")
         */
        title: string;
        /**
         * Describe your expertise in this area.
         */
        description?: string | null;
        /**
         * Years specializing in this area.
         */
        yearsInField?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Average rating (0-5)
   */
  rating?: number | null;
  /**
   * Total number of reviews
   */
  ratingCount?: number | null;
  /**
   * Total profile page views
   */
  profileViews?: number | null;
  responseTime?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lawyer-media".
 */
export interface LawyerMedia {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeSnippetBlockType".
 */
export interface CodeSnippetBlockType {
  /**
   * A friendly name to identify this code snippet in the CMS dashboard.
   */
  identifier: string;
  /**
   * Paste your raw HTML, CRM widgets, or tracking scripts here. Be careful, this renders exactly as provided.
   */
  htmlCode: string;
  /**
   * Control where and on which devices this block appears.
   */
  visibility?: {
    showOnDesktop?: boolean | null;
    showOnMobile?: boolean | null;
    targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
    targetPages?: (number | Page)[] | null;
    targetServices?: (number | Service)[] | null;
    targetLocations?: (number | Location)[] | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'codeSnippet';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlockType".
 */
export interface LogosBlockType {
  heading?: string | null;
  logos?:
    | {
        /**
         * Please upload an image with a 1:1 aspect ratio (Square) for the best visual display.
         */
        image: number | Media;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Control where and on which devices this block appears.
   */
  visibility?: {
    showOnDesktop?: boolean | null;
    showOnMobile?: boolean | null;
    targetType?: ('global' | 'selectedPages' | 'selectedServices' | 'selectedLocations') | null;
    targetPages?: (number | Page)[] | null;
    targetServices?: (number | Service)[] | null;
    targetLocations?: (number | Location)[] | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'logos';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  /**
   * The service they are inquiring about
   */
  service?: (number | null) | Service;
  /**
   * The city/location they searched from
   */
  location?: (number | null) | Location;
  message?: string | null;
  /**
   * The lawyer this enquiry is for
   */
  lawyer?: (number | null) | Lawyer;
  /**
   * The URL from which this lead was generated
   */
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'lawyers';
        value: number | Lawyer;
      } | null)
    | ({
        relationTo: 'lawyer-media';
        value: number | LawyerMedia;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  supabaseId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  seoTitle?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              layoutStyle?: T;
              heading?: T;
              subheading?: T;
              backgroundType?: T;
              backgroundImage?: T;
              backgroundColor?: T;
              textColorTheme?: T;
              showSearchBar?: T;
              ctaText?: T;
              ctaLink?: T;
              secondaryCta?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              style?: T;
              showStatsBar?: T;
              stats?:
                | T
                | {
                    icon?: T;
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richContent?:
          | T
          | {
              content?: T;
              maxWidth?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              description?: T;
              source?: T;
              faqs?: T;
              autoScope?: T;
              style?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        highlights?:
          | T
          | {
              sectionStyle?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              columns?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whyChooseUs?:
          | T
          | {
              heading?: T;
              subheading?: T;
              benefits?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              trustBadges?:
                | T
                | {
                    badgeText?: T;
                    id?: T;
                  };
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        registrationLicenses?:
          | T
          | {
              badge?: T;
              heading?: T;
              subheading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              ctaSection?:
                | T
                | {
                    ctaHeading?: T;
                    ctaSubheading?: T;
                    ctaButtonText?: T;
                    ctaLink?: T;
                  };
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        howItWorks?:
          | T
          | {
              processLabel?: T;
              heading?: T;
              backgroundImage?: T;
              quoteText?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              ctaText?: T;
              ctaLink?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        consultation?:
          | T
          | {
              formHeading?: T;
              formSubheading?: T;
              image?: T;
              imageHeading?: T;
              imageSubheading?: T;
              trustText?: T;
              ctaButtonText?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              backgroundImage?: T;
              style?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        blogFeed?:
          | T
          | {
              heading?: T;
              source?: T;
              service?: T;
              location?: T;
              category?: T;
              selectedBlogs?: T;
              limit?: T;
              layout?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsFeed?:
          | T
          | {
              heading?: T;
              source?: T;
              service?: T;
              location?: T;
              category?: T;
              selectedNews?: T;
              limit?: T;
              layout?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        galleryBlock?:
          | T
          | {
              heading?: T;
              source?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              gallery?: T;
              layout?: T;
              columns?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialsBlock?:
          | T
          | {
              heading?: T;
              description?: T;
              testimonials?: T;
              limit?: T;
              layout?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesCarousel?: T | ServicesCarouselBlockTypeSelect<T>;
        lawyersCarousel?:
          | T
          | {
              heading?: T;
              lawyers?: T;
              autoplay?: T;
              interval?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        codeSnippet?: T | CodeSnippetBlockTypeSelect<T>;
        logos?: T | LogosBlockTypeSelect<T>;
        documents?:
          | T
          | {
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    content?: T;
                    note?: T;
                    id?: T;
                  };
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  service?: T;
  location?: T;
  assignedBlogs?: T;
  assignedNews?: T;
  assignedFAQs?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsMeta?: T;
        schemaMarkup?: T;
      };
  status?: T;
  pageType?: T;
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServicesCarouselBlockType_select".
 */
export interface ServicesCarouselBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        service?: T;
        overrideIcon?: T;
        backgroundImage?: T;
        highlights?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  visibility?:
    | T
    | {
        showOnDesktop?: T;
        showOnMobile?: T;
        targetType?: T;
        targetPages?: T;
        targetServices?: T;
        targetLocations?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeSnippetBlockType_select".
 */
export interface CodeSnippetBlockTypeSelect<T extends boolean = true> {
  identifier?: T;
  htmlCode?: T;
  visibility?:
    | T
    | {
        showOnDesktop?: T;
        showOnMobile?: T;
        targetType?: T;
        targetPages?: T;
        targetServices?: T;
        targetLocations?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LogosBlockType_select".
 */
export interface LogosBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  logos?:
    | T
    | {
        image?: T;
        link?: T;
        id?: T;
      };
  visibility?:
    | T
    | {
        showOnDesktop?: T;
        showOnMobile?: T;
        targetType?: T;
        targetPages?: T;
        targetServices?: T;
        targetLocations?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              layoutStyle?: T;
              heading?: T;
              subheading?: T;
              backgroundType?: T;
              backgroundImage?: T;
              backgroundColor?: T;
              textColorTheme?: T;
              showSearchBar?: T;
              ctaText?: T;
              ctaLink?: T;
              secondaryCta?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              style?: T;
              showStatsBar?: T;
              stats?:
                | T
                | {
                    icon?: T;
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richContent?:
          | T
          | {
              content?: T;
              maxWidth?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              description?: T;
              source?: T;
              faqs?: T;
              autoScope?: T;
              style?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        highlights?:
          | T
          | {
              sectionStyle?: T;
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              columns?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whyChooseUs?:
          | T
          | {
              heading?: T;
              subheading?: T;
              benefits?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              trustBadges?:
                | T
                | {
                    badgeText?: T;
                    id?: T;
                  };
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        registrationLicenses?:
          | T
          | {
              badge?: T;
              heading?: T;
              subheading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?: T;
                    id?: T;
                  };
              ctaSection?:
                | T
                | {
                    ctaHeading?: T;
                    ctaSubheading?: T;
                    ctaButtonText?: T;
                    ctaLink?: T;
                  };
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        howItWorks?:
          | T
          | {
              processLabel?: T;
              heading?: T;
              backgroundImage?: T;
              quoteText?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              ctaText?: T;
              ctaLink?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        consultation?:
          | T
          | {
              formHeading?: T;
              formSubheading?: T;
              image?: T;
              imageHeading?: T;
              imageSubheading?: T;
              trustText?: T;
              ctaButtonText?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              description?: T;
              primaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              secondaryButton?:
                | T
                | {
                    text?: T;
                    link?: T;
                  };
              backgroundImage?: T;
              style?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        blogFeed?:
          | T
          | {
              heading?: T;
              source?: T;
              service?: T;
              location?: T;
              category?: T;
              selectedBlogs?: T;
              limit?: T;
              layout?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsFeed?:
          | T
          | {
              heading?: T;
              source?: T;
              service?: T;
              location?: T;
              category?: T;
              selectedNews?: T;
              limit?: T;
              layout?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        galleryBlock?:
          | T
          | {
              heading?: T;
              source?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              gallery?: T;
              layout?: T;
              columns?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonialsBlock?:
          | T
          | {
              heading?: T;
              description?: T;
              testimonials?: T;
              limit?: T;
              layout?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        servicesCarousel?: T | ServicesCarouselBlockTypeSelect<T>;
        lawyersCarousel?:
          | T
          | {
              heading?: T;
              lawyers?: T;
              autoplay?: T;
              interval?: T;
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
        codeSnippet?: T | CodeSnippetBlockTypeSelect<T>;
        logos?: T | LogosBlockTypeSelect<T>;
        documents?:
          | T
          | {
              heading?: T;
              description?: T;
              items?:
                | T
                | {
                    title?: T;
                    icon?: T;
                    content?: T;
                    note?: T;
                    id?: T;
                  };
              visibility?:
                | T
                | {
                    showOnDesktop?: T;
                    showOnMobile?: T;
                    targetType?: T;
                    targetPages?: T;
                    targetServices?: T;
                    targetLocations?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  banner?: T;
  activeLocations?: T;
  showInHeader?: T;
  menuOrder?: T;
  navDropdown?: T;
  navCategory?: T;
  navCategoryOrder?: T;
  navLabel?: T;
  icon?: T;
  uiIcon?: T;
  content?: T;
  highlights?:
    | T
    | {
        title?: T;
        description?: T;
        icon?: T;
        id?: T;
      };
  faqs?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsMeta?: T;
        schemaMarkup?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  service?: T;
  location?: T;
  message?: T;
  lawyer?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  excerpt?: T;
  featuredImage?: T;
  author?: T;
  categories?:
    | T
    | {
        category?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  services?: T;
  locations?: T;
  status?: T;
  publishedDate?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsMeta?: T;
        schemaMarkup?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  excerpt?: T;
  featuredImage?: T;
  author?: T;
  categories?:
    | T
    | {
        category?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  services?: T;
  locations?: T;
  status?: T;
  publishedDate?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogImage?: T;
        canonicalUrl?: T;
        robotsMeta?: T;
        schemaMarkup?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  scope?: T;
  service?: T;
  location?: T;
  page?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  designation?: T;
  content?: T;
  rating?: T;
  photo?: T;
  service?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  category?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lawyers_select".
 */
export interface LawyersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  email?: T;
  phone?: T;
  supabaseId?: T;
  status?: T;
  statusNote?: T;
  isSponsored?: T;
  isPremiumPartner?: T;
  photo?: T;
  designation?: T;
  bio?: T;
  barCouncilId?: T;
  experience?: T;
  consultationFee?: T;
  availableHours?: T;
  locationText?: T;
  courts?: T;
  location?: T;
  languages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  education?:
    | T
    | {
        degree?: T;
        college?: T;
        year?: T;
        id?: T;
      };
  specializations?:
    | T
    | {
        service?: T;
        title?: T;
        description?: T;
        yearsInField?: T;
        id?: T;
      };
  rating?: T;
  ratingCount?: T;
  profileViews?: T;
  responseTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lawyer-media_select".
 */
export interface LawyerMediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}